# Generated by Django 5.2.8 on 2025-12-01 19:36

import django.db.models.deletion
import django.utils.timezone
import shorts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=shorts.models.generate_code, editable=False, max_length=20, unique=True)),
                ('target', models.URLField()),
                ('label', models.CharField(blank=True, max_length=250)),
                ('private', models.BooleanField(default=False)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shorts.short')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('short', 'date', 'ip'), name='uniq_short_date_ip')],
            },
        ),
    ]
