# Generated by Django 5.2.8 on 2025-11-27 17:44

import django.core.validators
import django.db.models.deletion
import shorts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortStats',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.CharField(default=shorts.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('url', models.URLField()),
                ('private', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorts.shortstats')),
            ],
        ),
    ]
