# Generated by Django 5.2.8 on 2025-12-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short',
            old_name='expire_at',
            new_name='expired_at',
        ),
    ]
