# Generated by Django 5.2.8 on 2025-12-02 12:29

import django.core.validators
import shorts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_rename_expire_at_short_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='code',
            field=models.CharField(default=shorts.models.generate_code, editable=False, max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
