# Generated by Django 5.2.8 on 2025-12-02 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_alter_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shorts.short')),
            ],
        ),
        migrations.DeleteModel(
            name='ShortStats',
        ),
    ]
